package com.anonymous.designsystem.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF2CC78A)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF6DFCBA)
val light_onPrimaryContainer = Color(0xFF1F8B60)
val light_secondary = Color(0xFF2C57C7)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFDAE1FF)
val light_onSecondaryContainer = Color(0xFF2246A3)
val light_error = Color(0xFFE0395D)
val light_onError = Color(0xFFFFFFFF)
val light_background = Color(0xFFF7F9FA)
val light_onBackground = Color(0xFF272A2F)
val light_surface = Color(0xFFFFFFFF)
val light_onSurface = Color(0xFF272A2F)
val light_surfaceVariant = Color(0xFFF7F9FA)
val light_onSurfaceVariant = Color(0xFF7D7F82)
val light_outline = Color(0xFFEDF0F4)
val LightAppBar = Color(0xFF2CC78A)

val dark_primary = Color(0xFF2CC78A)
val dark_onPrimary = Color(0xFFFFFFFF)
val dark_primaryContainer = Color(0xFF005234)
val dark_onPrimaryContainer = Color(0xFF60E5B0)
val dark_secondary = Color(0xFF2C57C7)
val dark_onSecondary = Color(0xFFFFFFFF)
val dark_secondaryContainer = Color(0xFF7AA0FF)
val dark_onSecondaryContainer = Color(0xFF0C3D99)
val dark_error = Color(0xFFCE3A5A)
val dark_onError = Color(0xFFFFFFFF)
val dark_background = Color(0xFF121219)
val dark_onBackground = Color(0xFFFFFFFF)
val dark_surface = Color(0xFF191921)
val dark_onSurface = Color(0xFFFFFFFF)
val dark_surfaceVariant = Color(0xFF22222B)
val dark_onSurfaceVariant = Color(0xFF696978)
val dark_outline = Color(0xFFEDF0F4)
val DarkAppBar = Color(0xFF1D1D26)
