package com.android.chandchand.domain.entities

import com.android.chandchand.presentation.predictions.Winner

data class PredictionsEntity(
    val match_winner: Winner,
    val under_over: String?,
    val goals_home: String?,
    val goals_away: String?,
    val advice: String?,
    val winning_percent_home: String,
    val draws_percent: String,
    val winning_percent_away: String,
    val home_team_id: Int,
    val home_team_name: String,
    val away_team_id: Int,
    val away_team_name: String,
    val last_h2h_played_home: Int?,
    val last_h2h_wins_home: Int?,
    val last_h2h_draws_home: Int?,
    val last_h2h_loses_home: Int?,
    val last_h2h_played_away: Int?,
    val last_h2h_wins_away: Int?,
    val last_h2h_draws_away: Int?,
    val last_h2h_loses_away: Int?,
    val comparison_home_forme: String?,
    val comparison_home_att: String?,
    val comparison_home_def: String?,
    val comparison_home_fish_law: String?,
    val comparison_home_h2h: String?,
    val comparison_home_goals_h2h: String?,
    val comparison_away_forme: String?,
    val comparison_away_att: String?,
    val comparison_away_def: String?,
    val comparison_away_fish_law: String?,
    val comparison_away_h2h: String?,
    val comparison_away_goals_h2h: String?,
    val comparison_home_forme_number: Int?,
    val comparison_home_att_number: Int?,
    val comparison_home_def_number: Int?,
    val comparison_home_fish_law_number: Int?,
    val comparison_home_h2h_number: Int?,
    val comparison_home_goals_h2h_number: Int?,
    val comparison_away_forme_number: Int?,
    val comparison_away_att_number: Int?,
    val comparison_away_def_number: Int?,
    val comparison_away_fish_law_number: Int?,
    val comparison_away_h2h_number: Int?,
    val comparison_away_goals_h2h_number: Int?
)